# version: '3'

services:
  frontend:
      container_name: front
      build: ./front
      ports:
        - "8080:80"
        - "8443:8443"
      networks:
        - my-net
      depends_on:
        - web  # Make sure the backend is running
        - backend
      volumes:
        - ./front:/usr/share/nginx/html
        - media_volume:/usr/share/nginx/media  #  Nginx config

  web:
    container_name: web
    build: ./project
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on: 
      - db
      - gethnode
    env_file:
      - .env
    networks:
      - my-net
    volumes:
      - ./project:/usr/src/app
      - media_volume:/app/media 


  db:
    container_name: database
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-net

  backend:
      container_name: backend
      build: ./backend
      image: backend
      restart: always
      ports:
        - "8001:8001"
      volumes:
        - ./backend:/backend
      networks:
        - my-net
      env_file:
        - .env
      environment:
        - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
        - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}

  chat:
      build: ./ChatBackend
      command: ["./wait-for-it.sh", "redis:6379", "--", "daphne", "-b", "0.0.0.0", "-p", "8002", "chatapp.asgi:application"]
      ports:
        - "8002:8002"
      networks:
        - my-net
      volumes:
        - ./ChatBackend:/app
      depends_on:
        - redis
        - db
      environment:
        - DJANGO_SETTINGS_MODULE=chatapp.settings
      env_file:
        - .env

  redis:
    image: redis:6
    ports:
      - "6378:6379"
    networks:
    - my-net

  gethnode:
    build: ./geth
    container_name: gethnode
    ports:
      - "8545:8545"
    volumes:
      - ./geth/gethdata:/root/.ethereum
      - ./geth/init_wallet.sh:/root/init_wallet.sh
    networks:
      - my-net

volumes:
  postgres_data:
  media_volume:

networks:
  my-net:
    name: my-net
    driver: bridge