# version: '3'

services:
  frontend:
      container_name: front
      build: ./front  # Assuming the frontend Dockerfile is in a folder named 'frontend'
      ports:
        - "8080:80"
      # volumes:
      #   - ./frontend:/usr/share/nginx/html
      networks:
        - my-net
      depends_on:
        - web  # Make sure the backend is running
  web:
    container_name: web
    build: ./project
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on: 
      - db
    environment:
      - DB_NAME=ft_transcandencedb
      - DB_USER=othmane
      - DB_PASSWORD=otitebah1234
      - DB_HOST=db
      - DB_PORT=5432
      - private_key=08fdb79d0797a2f3be23e65c04b7ea373873132a8b0c1952298ebd103dafa656
      #private_key khass ikoun f .env
    # volumes:
    #   - ./media:/app/media  # Mount the media directory
    networks:
      - my-net

  db:
    container_name: database
    image: postgres:14
    environment:
      POSTGRES_DB: ft_transcandencedb
      POSTGRES_USER: othmane
      POSTGRES_PASSWORD: otitebah1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-net

volumes:
  postgres_data:

networks:
  my-net: